In [ ]:
תיאור: צרי מערך של 10 מספרים שלמים באקראי בין 1 ל-50. בדקי את גודל המערך, סוג הנתונים ומספר הממדים שלו.

In [ ]:
תיאור: צרי מערך דו-ממדי עם 2 שורות ו-5 עמודות של מספרים אקראיים בין 10 ל-100. בדקי את הצורה של המערך.

In [ ]:
pip install numpy

In [3]:
import numpy as np

In [8]:
array = np.random.randint( 1, 50 , size=(10))

In [9]:
array

array([ 1, 14, 25, 20, 48, 20, 34, 21,  9,  3])

In [10]:
array.size

10

In [11]:
array.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [12]:
array.dtype

dtype('int32')

In [13]:
np.ndim(array)

1

In [18]:
array.mean

<function ndarray.mean>

In [19]:
np.mean(array)

19.5

In [23]:
mat1 = np.random.randint(10,100, size=(3,3))

In [24]:
mat1

array([[64, 42, 33],
       [24, 37, 35],
       [23, 21, 92]])

In [27]:
mat = np.random.randint(10,100, size=(3,3))

In [14]:
mat

NameError: name 'mat' is not defined

In [20]:
np.add(mat, mat1)

NameError: name 'mat1' is not defined

mat

In [16]:
mat

array([[91, 16, 42, 75, 78],
       [21, 19, 32, 87, 52]])

In [17]:
mat.shape

(2, 5)

In [25]:
np.add(mat, mat1)

ValueError: operands could not be broadcast together with shapes (2,5) (3,3) 

In [28]:
np.add(mat, mat1)

array([[129,  55,  76],
       [ 68,  60,  48],
       [ 61,  83, 148]])

In [29]:
x = np.add(mat, mat1)

In [30]:
x.mean

<function ndarray.mean>

In [31]:
np.mean(x)

80.88888888888889

In [43]:
array2 = np.random.randint(1, 100, size=(20))

In [44]:
array2

array([97, 83, 52, 83,  3, 36, 88, 48, 37, 85, 71, 36, 44,  5, 75, 48, 32,
       15, 32,  9])

In [47]:
filtered_arr = array2[array2>50]

In [48]:
filtered_arr

array([97, 83, 52, 83, 88, 85, 71, 75])

In [53]:
np.random.shuffle(array2)

In [54]:
array2

array([75, 48, 88, 85, 32,  3, 15, 44, 83, 37, 97, 83,  5, 36, 71, 32, 36,
       48,  9, 52])